### ISSUE TITLE
behavior subclasses

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#14]
Many of the subclasses of `behavior` seem unnecessary. E.g. `adult behavior`). We probably should remove these.

**Comment by yongqunh** [comment]
Some explanation:
We imported many GO terms such as 'adult walking behavior':
http://www.ontobee.org/ontology/CIDO?iri=http://purl.obolibrary.org/obo/GO_0007628
because it involves the protein 'D(2) dopamine receptor (human)'
has participant some D(2) dopamine receptor (human)
which is related to many anticoronavirus drugs as seen here:  
http://www.ontobee.org/ontology/CIDO?iri=http://purl.obolibrary.org/obo/PR_P14416
example usage:
chlorpromazine subClassOf : chemical has protein target as antagonist some D(2) dopamine receptor (human)
Chlorpromazine / Dipyrone Oral Solution subClassOf : drug has protein target as antagonist some D(2) dopamine receptor (human)
fluphenazine subClassOf : chemical has protein target as antagonist some D(2) dopamine receptor (human)
Fluphenazine Oral Tablet subClassOf : drug has protein target as antagonist some D(2) dopamine receptor (human)
promethazine subClassOf : chemical has protein target as antagonist some D(2) dopamine receptor (human)
Promethazine Oral Tablet subClassOf : drug has protein target as antagonist some D(2) dopamine receptor (human)
Thiethylperazine subClassOf : drug has protein target as antagonist some D(2) dopamine receptor (human)
Thiothixene subClassOf : drug has protein target as antagonist some D(2) dopamine receptor (human)
Thiothixene subClassOf : chemical has protein target as antagonist some D(2) dopamine receptor (human)
Triflupromazine subClassOf : drug has protein target as antagonist some D(2) dopamine receptor (human)

So initially we added our manually curated drugs, then added drug target proteins (as seen in DrugBank and other resource), and then ran a GO enrichment analysis, and imported the enriched GO Biological process terms, and then make a link from the GO term --> proteins --> drug...
So the GO terms were added from the above algorithm.

**Comment by yongqunh** [comment]
A possible usage would be to query:
what anticoronaviral drugs can help for improving behavior?
then we can find all drugs that have proteins that participate in behavior processes.

**Comment by wdduncan** [comment]
Thanks @yongqunh. 
To be clear, I'm not saying the extra classes are a mistake. Rather, the other classes may overly complicate the ontology. If data is actually collected about walking behavior, perhaps this class is useful.

**Comment by yongqunh** [comment]
I agree that we do not want to overly complicate the ontology. My explanation and use case demo may justify the inclusion of some behavior classes like the walking behavior. Thanks @wdduncan!

**Comment by linikujp** [comment]
Not sure if I can still follow-up because this issue is closed. Where does
the antiviral drugs relation with behavior come from? I think the ontology
should capture fact, if the relation is predicted by informatics method, it
should be explicitly defined in the ontology.

Thanks,
Asiyah

We need to
